# Generated by Django 4.1.2 on 2022-10-31 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestioncontrat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Convention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=10)),
                ("objet", models.TextField(blank=True, null=True)),
                ("montant", models.FloatField()),
                ("duree", models.CharField(max_length=10)),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("nombre_renouv", models.IntegerField(blank=True, null=True)),
                ("date_renouvel", models.DateField(blank=True, null=True)),
                ("date_alerte", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="uploads_files/"),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "partenaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestioncontrat.partenaire",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestioncontrat.structure",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestioncontrat.type",
                    ),
                ),
            ],
        ),
    ]
