# Generated by Django 4.1.2 on 2022-12-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionconvention", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="archive",
            field=models.BooleanField(default=False),
        ),
    ]
