# Generated by Django 4.1.2 on 2022-11-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("telephone", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigle", models.CharField(blank=True, max_length=100, null=True)),
                ("nom", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Travail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=10)),
                ("objet", models.TextField(blank=True, null=True)),
                ("nature", models.CharField(blank=True, max_length=100, null=True)),
                ("matricule", models.CharField(blank=True, max_length=10, null=True)),
                ("nom", models.CharField(max_length=60)),
                ("prenom", models.CharField(max_length=80)),
                ("montant", models.FloatField()),
                ("duree", models.CharField(max_length=10)),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("nombre_renouv", models.IntegerField(blank=True, null=True)),
                ("date_renouvel", models.DateField(blank=True, null=True)),
                ("lieu", models.CharField(blank=True, max_length=100, null=True)),
                ("date_alerte", models.DateField()),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="uploads_files/"),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "partenaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestioncontrat.partenaire",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestioncontrat.structure",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestioncontrat.type",
                    ),
                ),
            ],
        ),
    ]
