# Generated by Django 4.1.2 on 2022-12-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestioncontrat", "0002_travail_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travail",
            name="archive",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
